on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy Code
      uses: appleboy/ssh-action@master
      with:
        host: 54.166.58.38
        username: test
        password: admin
        script: sudo cd /var/www/html && sudo git clone git@github.com:Divyakguar/node.git && sudo cp -r node/* .
